---
- hosts: all
  vars:
    users:
      - "ansible"
      - "node"
    pubs:
      - "ansible_ed25519.pub"
      - "node_ed25519.pub"
  tasks:
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
        groups: "wheel"
      with_items: "{{ users }}"

    - name: create ssh dir 
      file:
        path: "/home/{{ item }}/.ssh/"
        owner: "{{ item }}"
        state: directory
      with_items: "{{ users }}"

    - name: copy public keys
      copy:
        src: "/home/z/github/ewm/ansible/files/{{ item.1 }}"
        dest: "/home/{{ item.0 }}/.ssh/{{ item.1 }}"
        remote_src: False
      with_together:
        - "{{ users }}"
        - "{{ pubs }}"

