---
- hosts: all
  vars:
    users:
      - "ansible"
      - "node"
    pubs:
      - "ansible_ed25519.pub"
      - "node_ed25519.pub"
  tasks:
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
        groups: "wheel"
      with_items: "{{ users }}"

    - name: auth keys | ansible
      authorized_key:
        user: "ansible"
        key: "{{ lookup('file', '/home/z/github/ewm/ansible/files/ansible_ed25519.pub') }}"
    - name: auth keys | node
      authorized_key:
        user: "node"
        key: "{{ lookup('file', '/home/z/github/ewm/ansible/files/node_ed25519.pub') }}"
